config/routes.rb
Rails.application.routes.draw do
  #root 'x#y' sets the Default Page(localhost:3000) to the X Controller with Y action 
  root 'jobs#index'
  resources :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :description, presence: { message: "Required"}
  validates :title, presence: {message: "Required"}
  validates :salary, presence: {message: "Required"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.create(job_params)
    # if job is saved, redirect to index page w/ saved job
    if @job.save
      redirect_to jobs_path
    else
    # else render new 'new job page' w/ error message displayed via rendered 'form'
      render 'new'
  end
  end

  # edit - sets @job(instance) to the Job found by ID parameter
  # *** localhost:3000/jobs/id/edit *** --> URL
  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update_attributes(job_params)
    redirect_to jobs_path
  end

  def destroy
    @job = Job.find(params[:id])
    @job.delete
    redirect_to jobs_path
  end

  def show
    @job = Job.find(params[:id])
  end
  private
  def job_params
    params.require(:job).permit(:title, :description, :salary)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>

  <% if @job.errors.any? %>
    <% @job.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :salary %>
    <%= f.text_field :salary %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1> Edit Posting </h1>
<%# render takes the form in _form.html.erb and copies it into any view you "render" it in.  %>
<%= render "form" %>

app/views/jobs/index.html.erb
<h1> Job Board </h1>

<% @jobs.each do |job| %>
  <h3><%= link_to job.title, job_path(job)%></h3>
  <p><%= job.salary %></p>
  <p><%= job.description %></p>
<% end %>

app/views/jobs/new.html.erb
<h1> Add job posting </h1>
<%= render "form" %>

app/views/jobs/show.html.erb
<h1> Job Page</h1>

  <h3><%= @job.title %></h3>
  <p><%= @job.description %></p>
  <h5><%= link_to "Edit Job Posting", edit_job_path(@job) %> </h5>
  <h5><%= link_to "Delete Job Posting", @job, method: :delete %></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class='clearfix'>
  <div class="left-nav">
    <ul>
      <li><%= link_to "Home", jobs_path %></li>
    </ul>
  </div>
  <div class="right-nav">
    <ul>
      <li><%= link_to "Add Job", new_job_path %></li>
    </ul>
  </div>
</header>
<div class='content'>
<%= yield %>
</div>
  </body>
</html>